pipeline {
    agent {
        docker {
            image 'docker:24.0.5'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        FRONTEND_IMAGE = "frontend-app:latest"
        BACKEND_IMAGE  = "backend-app:latest"
        DB_IMAGE       = "mysql:8.0"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/Jenkins-Zero-To-Hero/three-tier-app',
                    branch: 'main'
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh '''
                  cd frontend
                  docker build -t $FRONTEND_IMAGE .
                '''
            }
        }

        stage('Build Backend Image') {
            steps {
                sh '''
                  cd backend
                  docker build -t $BACKEND_IMAGE .
                '''
            }
        }

        stage('Run MySQL') {
            steps {
                sh '''
                  docker rm -f mysql-db || true
                  docker run -d --name mysql-db \
                    -e MYSQL_ROOT_PASSWORD=root \
                    -e MYSQL_DATABASE=appdb \
                    -p 3306:3306 \
                    $DB_IMAGE
                '''
            }
        }

        stage('Run Backend') {
            steps {
                sh '''
                  docker rm -f backend-app || true
                  docker run -d --name backend-app \
                    -p 8080:8080 \
                    $BACKEND_IMAGE
                '''
            }
        }

        stage('Run Frontend') {
            steps {
                sh '''
                  docker rm -f frontend-app || true
                  docker run -d --name frontend-app \
                    -p 80:80 \
                    $FRONTEND_IMAGE
                '''
            }
        }
    }

    post {
        success {
            echo "✅ 3-Tier Application deployed successfully"
        }
        failure {
            echo "❌ Deployment failed"
        }
    }
}
