pipeline {
    agent any

    environment {
        IMAGE_NAME = "hello-world-java"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            agent {
                docker {
                    image 'maven:3.9.6-eclipse-temurin-8'
                }
            }
            steps {
                dir('hello-world3') {
                    sh 'mvn clean test package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('hello-world3') {
                    sh 'docker build -t $IMAGE_NAME:latest .'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker rm -f hello-world || true
                docker run -d --name hello-world hello-world-java:latest
                '''
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully 🚀"
        }
        failure {
            echo "Pipeline failed ❌"
        }
    }
}
