stage('Docker Build') {
    agent {
        docker {
            image 'docker:24.0.5'
            args '--entrypoint="" -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    environment {
        DOCKER_CONFIG = "${WORKSPACE}/.docker"
    }
    steps {
        dir('hello-world3') {
            sh 'docker build -t $IMAGE_NAME:latest .'
        }
    }
}

stage('Deploy') {
    agent {
        docker {
            image 'docker:24.0.5'
            args '--entrypoint="" -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    environment {
        DOCKER_CONFIG = "${WORKSPACE}/.docker"
    }
    steps {
        dir('hello-world3') {
            sh '''
            docker rm -f hello-world-container || true
            docker run -d --name hello-world-container $IMAGE_NAME:latest
            '''
        }
    }
}
