pipeline {
    agent {
        docker {
            image 'docker:24.0.5'
            args '-u root:root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        IMAGE_NAME = "java-hello-world"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Harish19977/Jenkins-Zero-To-Hero/hello-world'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                  docker build -t $IMAGE_NAME .
                '''
            }
        }

        stage('Run Java App') {
            steps {
                sh '''
                  docker run --rm $IMAGE_NAME
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Java app executed successfully inside Docker!"
        }
        failure {
            echo "❌ Pipeline failed"
        }
    }
}
