pipeline {
  agent any

  environment {
    IMAGE_NAME = "harish327/java-hello-world4"
    IMAGE_TAG  = "${BUILD_NUMBER}"
    REPO_URL   = "https://github.com/Harish19977/Jenkins-Zero-To-Hero.git"
  }

  stages {

    stage('Checkout Source Code') {
      steps {
        checkout scm
      }
    }

    stage('Build & Test (Maven Docker Agent)') {
      agent {
        docker {
          image 'maven:3.9.6-eclipse-temurin-17'
          args '-v /var/lib/jenkins/.m2:/root/.m2'
        }
      }
      steps {
        dir('java-hello-world4') {
          sh 'mvn clean package'
          sh 'mvn test'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('java-hello-world4') {
          sh '''
            docker build -t harish327/java-hello-world4:${BUILD_NUMBER} .
          '''
        }
      }
    }

    stage('Push Docker Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-creds',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push harish327/java-hello-world4:${BUILD_NUMBER}
          '''
        }
      }
    }

    stage('Update Kubernetes Manifest (GitOps)') {
      steps {
        withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
          sh '''
            rm -rf Jenkins-Zero-To-Hero

            git clone https://x-access-token:$GITHUB_TOKEN@github.com/Harish19977/Jenkins-Zero-To-Hero.git
            cd Jenkins-Zero-To-Hero/k8s-manifests

            sed -i "s|image: .*|image: harish327/java-hello-world4:${BUILD_NUMBER}|g" deployment.yaml

            git config user.email "jenkins@local"
            git config user.name "jenkins"

            git add deployment.yaml
            git commit -m "chore: update image to ${BUILD_NUMBER}"
            git push origin main
          '''
        }
      }
    }
  }
}
