pipeline {
  agent none

  environment {
    DOCKERHUB_USER = 'your_dockerhub_username'
    BACKEND_IMAGE = "${DOCKERHUB_USER}/backend"
    FRONTEND_IMAGE = "${DOCKERHUB_USER}/frontend"
    DOCKER_CONFIG = "${WORKSPACE}/.docker"
  }

  stages {

    stage('Checkout') {
      agent any
      steps {
        checkout scm
      }
    }

    stage('Build Application (Maven)') {
      agent {
        docker {
          image 'maven:3.9.6-eclipse-temurin-17'
        }
      }
      steps {
        sh '''
          cd three-tier-devops-app/backend
          mvn clean package -DskipTests
        '''
      }
    }

    stage('Build Docker Images') {
      agent {
        docker {
          image 'docker:26.0'
          args '-v /var/run/docker.sock:/var/run/docker.sock --user root'
        }
      }
      steps {
        sh '''
          mkdir -p "$DOCKER_CONFIG"

          docker info
          docker build -t $BACKEND_IMAGE:latest three-tier-devops-app/backend
          docker build -t $FRONTEND_IMAGE:latest three-tier-devops-app/frontend
        '''
      }
    }

    stage('DockerHub Login & Push') {
      agent {
        docker {
          image 'docker:26.0'
          args '-v /var/run/docker.sock:/var/run/docker.sock --user root'
        }
      }
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-creds',
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]) {
          sh '''
            echo "$PASS" | docker login -u "$USER" --password-stdin
            docker push $BACKEND_IMAGE:latest
            docker push $FRONTEND_IMAGE:latest
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      agent {
        docker {
          image 'bitnami/kubectl:latest'
          args '-v $HOME/.kube:/root/.kube'
        }
      }
      steps {
        sh '''
          kubectl get nodes
          kubectl apply -f three-tier-devops-app/k8s/mysql.yaml
          kubectl apply -f three-tier-devops-app/k8s/backend.yaml
          kubectl apply -f three-tier-devops-app/k8s/frontend.yaml
        '''
      }
    }
  }
}
