pipeline {
  agent none

  environment {
    DOCKERHUB_USER = 'harish327'
    BACKEND_IMAGE  = "${DOCKERHUB_USER}/backend"
    FRONTEND_IMAGE = "${DOCKERHUB_USER}/frontend"
    DOCKER_CLIENT_TIMEOUT = '600'
    COMPOSE_HTTP_TIMEOUT  = '600'
  }

  stages {

    stage('Checkout') {
      agent any
      steps {
        checkout scm
      }
    }

    stage('Build Application (Maven)') {
      agent {
        docker {
          image 'maven:3.9.6-eclipse-temurin-17'
          args '--user root'
        }
      }
      steps {
        sh '''
          cd three-tier-devops-app/backend
          mvn clean package -DskipTests
        '''
      }
    }

    stage('Build Docker Images') {
      agent {
        docker {
          image 'docker:26.0'
          args '-v /var/run/docker.sock:/var/run/docker.sock --user root'
        }
      }
      steps {
        sh '''
          docker info
          docker build -t $BACKEND_IMAGE:latest three-tier-devops-app/backend
          docker build -t $FRONTEND_IMAGE:latest three-tier-devops-app/frontend
        '''
      }
    }

    stage('Push Backend Image') {
      agent any
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-creds',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $BACKEND_IMAGE:latest
          '''
        }
      }
    }

    stage('Push Frontend Image') {
      agent any
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-creds',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            docker push $FRONTEND_IMAGE:latest
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      agent any
      steps {
        sh '''
          kubectl config use-context minikube
          kubectl get nodes

          kubectl apply -f three-tier-devops-app/k8s/mysql.yaml
          kubectl apply -f three-tier-devops-app/k8s/backend.yaml
          kubectl apply -f three-tier-devops-app/k8s/frontend.yaml
        '''
      }
    }
  }
}
