apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-hello-world
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Harish19977/Jenkins-Zero-To-Hero.git
    targetRevision: main
    path: k8s-manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
